#include<iostream>
#include<fstream>
#include<math.h>
using namespace std;

#define PI 3.14159265

int build_environment_map()
{
	//To initialize all the paramters by using data in the figure above
	double x0[5]={0.8,0.8,1.7,2.2,2.25};
	double y0[5]={1.5,2.25,1.0,1.3,0.25};
	double r=0.125, wallLength=2.5;
	double RD=PI/180;
	
	//Open a datafile "EnvironmentMap.txt" for storing walls, pillars and charger generated by your code
	ofstream map;
	map.open("EnvironmentMap2.txt");
	
	//The following code is to create a charger based on its centre
	for(int i=0;i<360;i=i+20){
	map<<x0[4]+r*cos(i*RD)<<' '<<y0[4]+r*sin(i*RD)<<endl;	
	}
	
	//put your code here to generate four circle pillars with the given centres
	for(int i=0;i<360;i=i+2){
	map<<x0[0]+r*cos(i*RD)<<' '<<y0[0]+r*sin(i*RD)<<endl;//first pillar
	map<<x0[1]+r*cos(i*RD)<<' '<<y0[1]+r*sin(i*RD)<<endl;//second pillar
	map<<x0[2]+r*cos(i*RD)<<' '<<y0[2]+r*sin(i*RD)<<endl;//third pillar
	map<<x0[3]+r*cos(i*RD)<<' '<<y0[3]+r*sin(i*RD)<<endl;//forth pillar
	}
	
	//For your reference, the following code is used to generate two walls
	
	//produces the bottom wall
	for(double j=0;j<wallLength;j=j+0.01){
	map<<wallLength<<' '<<j<<endl;//bottom wall
	map<<j<<' '<<0<<endl;//right wall	
	map<<j<<' '<<wallLength<<endl;//top wall
	map<<0<<' '<<j<<endl;//left wall
	}
	
	
	map.close();
	return 0;
}

int main(int argc, char **argv)
{
	int i;
	i = build_environment_map();
	return 0;
}
